# Generated by Django 5.0.4 on 2024-05-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_video_featured'),
        ('userauths', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved_videos',
            field=models.ManyToManyField(blank=True, to='core.video'),
        ),
    ]
