# Generated by Django 5.0.4 on 2024-05-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
