# Generated by Django 5.0.4 on 2024-05-26 21:01

import channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'Community', 'verbose_name_plural': 'Community Posts'},
        ),
        migrations.RemoveField(
            model_name='community',
            name='likes',
        ),
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=channel.models.user_directory_path),
        ),
    ]
